### ISSUE TITLE
JCenter sunset - what should be used as pluginrepository

### ISSUE THREAD

**Issue by vansickle** [jfrog/artifactory-maven-plugin#12]
We use the plugin to upload artifacts to Artifactory
Now it was announced that JCenter will sunset on May 1st https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ but official documentation for the plugin still recommends to use jcenter as pluginrepository
What should be used instead?

**Comment by yahavi** [comment]
@vansickle,
Thank you for pointing that out.
During the Maven Artifactory plugin release, we upload the plugin Jar to Artifactory in https://oss.jfrog.org and then distribute it to Bintray. Therefore, we can use https://oss.jfrog.org as the repository source of the plugin:
```xml
<pluginRepositories>
    <pluginRepository>
        <id>jfrog-plugins-release</id>
        <name>plugins-release</name>
        <url>https://oss.jfrog.org/artifactory/plugins-release</url>
    </pluginRepository>
</pluginRepositories>
```

You can find an example [here](https://github.com/jfrog/project-examples/blob/master/artifactory-maven-plugin-example/pom.xml).
We will update the documentation as well.

**Comment by vansickle** [comment]
@yahavi Thank you, it's clear now

**Comment by yahavi** [comment]
@vansickle,
We recently started to upload the Maven Artifactory plugin to Maven Central. That is the global default Maven dependencies repository. Therefore, from now on, the https://oss.jfrog.org/artifactory/plugins-release plugin repository is not mandatory anymore.

For more information see: https://search.maven.org/artifact/org.jfrog.buildinfo/artifactory-maven-plugin/3.2.1/maven-plugin

**Comment by rmkanda** [comment]
The https://oss.jfrog.org/artifactory/plugins-release plugin repository is not available. 
if you are using older version of the plugin (which is not available in maven central) you can use
https://oss.jfrog.org/artifactory/jfrog-jars/org/jfrog/buildinfo/artifactory-maven-plugin/

```
    <pluginRepositories>
        <pluginRepository>
            <id>jfrog-jars</id>
            <name>jfrog-plugins</name>
            <url>https://oss.jfrog.org/artifactory/jfrog-jars</url>
        </pluginRepository>
    </pluginRepositories>
```
