### ISSUE TITLE
Enable deployment through HTTP proxy

### ISSUE THREAD

**Issue by OliverMatz** [jfrog/artifactory-maven-plugin#14]
Our maven build runs on a machine that can connect to the internet only via an HTTP-proxy.  The target nexus artifactory is only available via the internet.  Although the http proxy is correctly configured (1) in the file `.m2/settings.xml` and (2) in the four environment variables `[http[s]_(proxy|port)]` and (3) in the four java standard system properties `http[s].proxy(Host|Port)`, the artifactory-maven-plugin does not use and the attempt to deploy to the nexus artifactory fails with an exception:
{noformat}
[ERROR] Internal error: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error occurred while publishing artifact to Artifactory: ...
[ERROR]  Skipping deployment of remaining artifacts (if any) and build info. Connect to targethost.de:443 [targethost.de/111.22.33.44] failed: Connection timed out: connect
{noformat}

I would like to see some documented way to use the http proxy. Preferrably, the artifactory-maven-plugin should use the http proxy configured in the file .m2/settings.xml, but I would be happy with any other reliable way that somehow fits into the configuration framework.

**Additional context**
* This feature has been requested before: http://forums.jfrog.org/Maven-Artifactory-Plugin-setting-http-proxy-td7579782.html
* Other maven plugins do use our http proxy correctly
* There is quite a lot of preparation in the present code (3.2.1), e.g. class org.jfrog.build.extractor.clientConfiguration.ArtifactoryClientConfiguration.ProxyHandler, but it does not seem to be actually used.
* I have found a simple fix that works for me and which I plan to submit as a pull request

**Comment by OliverMatz** [comment]
pending pull request: https://github.com/jfrog/artifactory-maven-plugin/pull/15

**Comment by yahavi** [comment]
@OliverMatz,
Thanks for reporting this issue.

Maven Artifactory plugin 3.2.3 is released. 
This version should include the fix for this issue - feel free to upgrade.

We'd appreciate your feedback on that.
