### ISSUE TITLE
Publishing Build Info to Projects Using the Maven Artifactory Plugin

### ISSUE THREAD

**Issue by samrjfrog** [jfrog/artifactory-maven-plugin#25]
We would like the ability to publish the build information from a Maven build to a specific project in Artifactory (as opposed to the general artifactory-build-info location) via the Artifactory Maven Plugin or customizable pom parameter.

Currently the only way to implement this is via the JFrog CLI which would greatly complicate our builds.

**Comment by jghal** [comment]
Is this duplicate of #21?

**Comment by sverdlov93** [comment]
Hi @samrjfrog,
artifactory-maven-plugin 3.4.0 is released and contains support for Artifactory Projects.
Looking forward to your feedback on it.
