### ISSUE TITLE
artifactory maven plugin not deploying poms for OSGi bundles (packageType=bundle)

### ISSUE THREAD

**Issue by bob-walters** [jfrog/artifactory-maven-plugin#38]
**Describe the bug**
deployment of OSGi bundles  (<package>=bundle in the pom.xml) results in the deployment only pushing the .jars, but it seems to ignore the .pom and does not push it to artifactory.

**To Reproduce**
Create an osgi-based project that uses the maven-bundle-plugin to build an OSGi bundle.  See https://felix.apache.org/documentation/subprojects/apache-felix-maven-bundle-plugin-bnd.html for example.  This results in a standard .jar, .-test.jar, *.pom, etc. being installed into the local mvn repository during 'install' processing.  However during 'deploy' via the artifactory maven plugin, only the .jar assets are deployed.    In contrast, the maven-deploy-plugin, if used as an alternative to the artifactory plugin will deploy the .pom as well as the jars.

**Expected behavior**
The .pom file should be pushed 

**Screenshots**
N/A

**Versions**
- Artifactory Maven plugin version: 3.4.0 and 3.2.3 (tried both)
- Artifactory version: Artifactory Professional 5.2.0 rev 50024
- Maven version: 3.3.9

**Additional context**

**Comment by odrotbohm** [comment]
I am seeing this happening for standard JAR artifacts as well. I have a project that [deploys POMs](https://github.com/spring-projects/spring-plugin/actions/runs/3059950246/jobs/4937908646) using the plugin in version 3.4.0. A different, identically set up project [does not](https://github.com/spring-projects-experimental/spring-modulith/actions/runs/3130757541/jobs/5081357287). Any pointers that could help to diagnose this further appreciated.

**Comment by mikaello** [comment]
@odrotbohm We are experiencing the same for our JAR artifacts.

This problem occurs only with `org.apache.maven.plugins:maven-deploy-plugin` version `3.0.0`, if you downgrade that plugin to `2.8.2` or lower, POM files are correctly published.

@odrotbohm , if you look at your projects you will see that the project that does deploy POMs uses v2.7: `--- maven-deploy-plugin:2.7:deploy (default-deploy) @ spring-plugin ---` , while the one that does not work uses v3.0.0: `maven-deploy-plugin:3.0.0:deploy (default-deploy) @ spring-modulith`.

**Workaround:**

```diff
       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-deploy-plugin</artifactId>
-        <version>3.0.0</version>
+        <version>2.8.2</version>
       </plugin>
```

**Comment by mikaello** [comment]
Sorry, I was blinded by multiple plugin upgrades, I have found that we also (or maybe only) needed to downgrade `maven-install-plugin`. 

```xml
       <plugin>
         <groupId>org.apache.maven.plugins</groupId>
         <artifactId>maven-install-plugin</artifactId>
-        <version>3.0.1</version>
+        <version>2.5.2</version>
       </plugin>
```

**Comment by yahavi** [comment]
@bob-walters @odrotbohm @mikaello,
Maven Artifactory plugin 3.5.1 is released. This version includes the [fix](https://github.com/jfrog/artifactory-maven-plugin/pull/46) for this issue.
Feel free to upgrade - we'd appreciate your feedback on that.
