### ISSUE TITLE
Deploys artifacts when `maven.deploy.skip` is `true`

### ISSUE THREAD

**Issue by TobiX** [jfrog/artifactory-maven-plugin#39]
**Describe the bug**

Deploys artifacts which should not be deployed.

**To Reproduce**

Create a multi-module Maven project where one module contains this config:
```
  <properties>
    <maven.deploy.skip>true</maven.deploy.skip>
  </properties>
```

**Expected behavior**

Modules marked with `maven.deploy.skip` should not be deployed.

**Screenshots**

**Versions**
- Artifactory Maven plugin version: 3.4.0
- Artifactory version:  7.37.17 
- Maven version: 3.8.6

**Additional context**

**Comment by pugangxa** [comment]
Encounter this too, will we fix this bug?

**Comment by NewLunarFire** [comment]
This property skips deployment for the maven-deploy-plugin and not for the artifactory-maven-plugin. The artifactory-maven-plugin automatically sets this property to false to avoid deploying artifacts twice. 

You need to add an additional parameter in the <publisher> section of your configuration that is: `<publishArtifacts>false</publishArtifacts>`

**Comment by yahavi** [comment]
@TobiX @pugangxa @NewLunarFire,
Thanks for using the Maven Artifactory plugin.

We are working on supporting the `maven.deploy.skip` property.
Could you please elaborate on the cause? Why would you use the deploy goal with `maven.deploy.skip=true`?
Would you expect the Maven Artifactory plugin to collect and publish the build-info when `maven.deploy.skip=true`?

We're looking forward to your answer!

**Comment by pugangxa** [comment]
In my case, I have a maven repo that has some sub modules, one module is for the code coverage report purpose so I do not want to publish anything on it, so I want to set `maven.deploy.skip` property in the sub-module level to skip it.

**Comment by yahavi** [comment]
Thanks, @pugangxa.
We created https://github.com/jfrog/artifactory-maven-plugin/pull/43 to fix this issue by skipping the deployment of the module's artifacts when there is a property in the module `<maven.deploy.skip>true</maven.deploy.skip>`.
Please let me know if you disagree with the change.

**Comment by TobiX** [comment]
My use case is similar to @pugangxa - There are some internal modules which don't publish any artifacts and the "conventional" way before adding this plugin to our standard Maven builds was to set that property (or configure the maven-deploy-plugin directly, but that's much less common, so I don't care if that use case is supported).
This has a bit to do with expectations: I wasn't expecting the Artifactory plugin to alter how my Maven workflow works in a basic way (I would have expected a plugin which modifies how the deployment of my projects work to implement something like a Maven Wagon plugin, not disabling the Maven Deploy plugin "from the outside"). Now that I understand how the plugin works I would expect it to at least mimic the `maven-deploy-plugin` behaviour as far as this property goes...

**Comment by yahavi** [comment]
@TobiX @pugangxa @NewLunarFire,
Maven Artifactory plugin 3.5.0 is released. This version includes the fix for this issue.
Feel free to upgrade - we'd appreciate your feedback on that.
