### ISSUE TITLE
HTTP Proxy not used 

### ISSUE THREAD

**Issue by pawl1234** [jfrog/artifactory-maven-plugin#59]
### Describe the bug

From our CI/CD Pipeline we need to use a proxy to access artifactory. In the /root/.m2/settings.xml there are proxy settings and they work to download plugin & dependencies. The artifactory-maven-plugin seem to ignore these settings and I dont find a documented way to use a proxy. 

### Current behavior

```
[WARNING] Error occurred for request GET /artifactory/api/system/version HTTP/1.1: Connect to artifactory.x.eu:443 [artifactory.x.eu/167.x.x.201] failed: Connection timed out.
[WARNING] Error occurred for request GET /artifactory/api/system/version HTTP/1.1: Connect to artifactory.x.eu:443 [artifactory.x.eu/167.x.x.201] failed: Connection timed out.
```
pom.xml
```
  <build>
    <plugins>
      <plugin>
        <groupId>org.jfrog.buildinfo</groupId>
        <artifactId>artifactory-maven-plugin</artifactId>
        <version>3.5.2</version>
        <inherited>false</inherited>
        <executions>
          <execution>
            <id>build-info</id>
            <goals>
              <goal>publish</goal>
            </goals>
            <configuration>
              <deployProperties>
                <build.timestamp>${maven.build.timestamp}</build.timestamp>
                <build.name>${project.artifactId}</build.name>
                <build.number>${buildNumber}</build.number>
              </deployProperties>
              <publisher>
                  <contextUrl>${ARTIFACTORY_URL}</contextUrl>
                  <username>${ARTIFACTORY_USER}</username>
                  <password>${ARTIFACTORY_PASSWORD}</password>
                  <repoKey>x-test-platform</repoKey>
                  <snapshotRepoKey>x-test-platform</snapshotRepoKey>
              </publisher>
              <proxy>
                <host>proxy.x.de</host>
                <port>x</port>
              </proxy>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```

### Artifactory Maven plugin version

3.5.2

### Operating system type and version

Ubuntu 20.04

**Comment by yahavi** [comment]
@pawl1234,
Thanks for reporting this issue.

To add this functionality we created #64. You're more than welcome to review and share your feedback.
We'd keep you updated about that once it gets merged and a new version is released.

As a workaround for now, you can populate the following system properties:
`artifactory.proxy.host`
`artifactory.proxy.port`
`artifactory.proxy.username`
`artifactory.proxy.password`

For example:
```
mvn clean install -Dartifactory.proxy.host=proxy.jfrog.io -Dartifactory.proxy.port=8888 -Dartifactory.proxy.username=proxyUser  -Dartifactory.proxy.password=proxyPass
```

Please let me know if the workaround helped.

**Comment by yahavi** [comment]
@pawl1234,
Maven Artifactory plugin 3.6.0 is released.
This version includes support for HTTP proxy OOTB - 
Either from settings.xml or from the pom.xml, per your request.
See usage at https://github.com/jfrog/artifactory-maven-plugin/pull/64. We'll describe it in the plugin's documentation soon.

We'd appreciate your feedback on that.

**Comment by pawl1234** [comment]
Great thank you @yahavi !
